sudo: required
services:
    - docker

before_install:
    - docker build -t danielchrislucas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true danielchrislucas/react-test npm test

after_success:
    - docker build -t danielchrislucas/multi-client ./client
    - docker build -t danielchrislucas/multi-nginx ./nginx
    - docker build -t danielchrislucas/multi-server ./server
    - docker build -t danielchrislucas/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push danielchrislucas/multi-client
    - docker push danielchrislucas/multi-nginx
    - docker push danielchrislucas/multi-server
    - docker push danielchrislucas/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'eu-west-3'
    app: 'multi-docker'
    env: 'Multidocker-env'
    bucket_name: 'elasticbeanstalk-eu-west-3-411531034811'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
